version: "3"

services:
  coupang:
    build:
      context: coupang-app/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./coupang-app:/app"
    expose:
      - "8080"
    environment:
      PYTHONDONTWRITEBYTECODE: 1      
    container_name: coupang
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - "coupang"
    container_name: nginx

volumes:
  static-volume: